// This file is auto-generated by scripts/sync-videos.js
// Do not edit manually. Run "npm run sync-videos" to refresh.

export type GeneratedBackgroundItem = {
  id: string;
  label: string;
  type: "image" | "video";
  src: string;
};

export const LOCAL_FOLDER_BACKGROUNDS: GeneratedBackgroundItem[] = [];
