import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

const publicVideosDir = path.join(rootDir, "public", "videos");
const publicPhotosDir = path.join(rootDir, "public", "photos");
const outputFile = path.join(rootDir, "src", "lib", "backgrounds.gen.ts");

// Ensure public directories exist
if (!fs.existsSync(publicVideosDir)) {
  fs.mkdirSync(publicVideosDir, { recursive: true });
}
if (!fs.existsSync(publicPhotosDir)) {
  fs.mkdirSync(publicPhotosDir, { recursive: true });
}

function getFiles(dir, extensions) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((file) => extensions.some((ext) => file.toLowerCase().endsWith(ext)))
    .map((file) => ({
      name: file,
      ext: path.extname(file),
      basename: path.basename(file, path.extname(file)),
    }));
}

const videoExts = [".mp4", ".webm", ".mov", ".mkv"];
const photoExts = [".jpg", ".jpeg", ".png", ".webp", ".avif"];

const videos = getFiles(publicVideosDir, videoExts);
const photos = getFiles(publicPhotosDir, photoExts);

function formatLabel(filename) {
  return filename.replace(/[-_]/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
}

const generatedItems = [
  ...videos.map((v, i) => ({
    id: `local_video_${i + 1}_${v.basename}`,
    label: formatLabel(v.basename),
    type: "video",
    src: `/videos/${v.name}`,
  })),
  ...photos.map((p, i) => ({
    id: `local_photo_${i + 1}_${p.basename}`,
    label: formatLabel(p.basename),
    type: "image",
    src: `/photos/${p.name}`,
  })),
];

const content = `// This file is auto-generated by scripts/sync-videos.js
// Do not edit manually. Run "npm run sync-videos" to refresh.

export type GeneratedBackgroundItem = {
  id: string;
  label: string;
  type: "image" | "video";
  src: string;
};

export const LOCAL_FOLDER_BACKGROUNDS: GeneratedBackgroundItem[] = ${JSON.stringify(generatedItems, null, 2)};
`;

fs.writeFileSync(outputFile, content, "utf-8");
console.log(
  `\x1b[32m[Tilawa Studio]\x1b[0m Synced ${videos.length} video(s) and ${photos.length} photo(s) from public/ folder into src/lib/backgrounds.gen.ts!`,
);
